"""
Django settings for loginNow project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import sys
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', default=False, cast=bool) # Use False if you do want page not found(404)

ALLOWED_HOSTS = config('DJANGO_ALLOWED_HOSTS', cast=Csv())


SECURE_HSTS_SECONDS = 31536000  # atau jangan set sama sekali(Kalau mau set pake 31536000 = 1 tahun!)
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_extensions',
    'django_smart_ratelimit',
    #'social_django',
    'django_recaptcha',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'guardian',
    'accounts',
    'base',
    'video_processor',
    'event',
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    #'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
    'guardian.backends.ObjectPermissionBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

RATELIMIT_BACKEND = 'database'

MIDDLEWARE_URL = "http://127.0.0.1:8001" 

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'social_django.middleware.SocialAuthExceptionMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'base.middleware.DisableBackAfterLogoutMiddleware',  #Cegah user bisa masuk ke home lagi setelah logout
]

ROOT_URLCONF = 'loginNow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'loginNow.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#===========================Gunakan ini hanya untuk testing saja! Jangan gunakan untuk produksi/deploy!==================
#===========================Buka ini jika ingin testing!================================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

#=======================Buka ini jika ingin dideploy/produksi==================
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': config('LOCAL_DATABASE'),
#        'USER': config('LOCAL_USERNAME'),
#        'PASSWORD': config('PASS_SQL'),
#        'HOST': config('SQL_HOST'),
#        'PORT': config('PORTO'),
#    }
#}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8, # Panjang minimal password
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'id' #'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': config('DJANGO_AUTH_GOOGLE_OAUTH2_KEY'),
            'secret': config('DJANGO_AUTH_GOOGLE_OAUTH2_SECRET'),
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {
            'access_type': 'online',
            'prompt': 'select_account',
            },
        'OAUTH_PKCE_ENABLED': True,
    }
}

ACCOUNT_FORMS = {
    'login': 'base.forms.CustomLoginForm',
    # Jika Anda ingin form pendaftaran kustom, tambahkan di sini:
    'signup': 'base.forms.CustomUserCreationForm', 
}

LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "account_login"

#ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_LOGIN_METHODS = ['email', 'username']
ACCOUNT_SIGNUP_FIELDS = ['username*', 'nomor_telepon*', 'password*', 'password2*']
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_ADAPTER = 'base.views.CustomAccountAdapter'
ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Dari Google Cloud Console
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config('DJANGO_AUTH_GOOGLE_OAUTH2_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config('DJANGO_AUTH_GOOGLE_OAUTH2_SECRET')
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
#SOCIALACCOUNT_EMAIL_VERIFICATION = ACCOUNT_EMAIL_VERIFICATION
SOCIALACCOUNT_ADAPTER = 'base.views.SocialAccountAdapter'

#Kirim Email (Paling utama buat OTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' #(Pake ini kalau mau kirim email beneran)
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' #(Pake ini kalau mau kirim email percobaan bukan sungguhan!)
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = config('DJANGO_EMAIL_PORT')
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'dederadeaajiprasojo@gmail.com'
EMAIL_HOST_PASSWORD = config('DJANGO_HOST_PASS')

#RECAPTCHA_V2
RECAPTCHA_PUBLIC_KEY = config('PUBLICKEY_RECAPTCHA')
RECAPTCHA_PRIVATE_KEY = config('PRIVATEKEY_RECAPTCHA')
RECAPTCHA_USE_SSL = True
AUTHENTICATION_FORM = 'base.forms.CaptchaLoginForm'

#RECAPTCHA_V3
RECAPTCHA_V3_SITE_KEY = config('PUBLICKEY_V3_RECAPTCHA')
RECAPTCHA_V3_SECRET_KEY = config('PRIVATEKEY_V3_RECAPTCHA')
RECAPTCHA_REQUIRED_SCORE = 0.85

#SMS_TOKEN
WA_API_TOKEN = config('WABLAS_API_KEY')
WA_SECRET_TOKEN = config('WABLAS_SECRET_KEY')

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# DOMAIN = '127.0.0.1:8000'  # atau ganti dengan domain aslimu saat deploy

# URL untuk mengakses file media di browser
MEDIA_URL = '/media/'

# Path absolut ke folder tempat file media akan disimpan
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTH_USER_MODEL = 'accounts.CustomUser'